sf:
  consumerKey: '![hruFlQiFUQEY4pHy6eWud3H0o23Mvr2Qega+LktIQtPmaRrKLaezXobO7+kvr86VUmA+aLmGoGuUeK8yjJjn/nE404fW0KMbZk0oG8DCMWqfe140KHxpWXLn2xGlwwJE]'
  consumerSecret: '![0xTLsuRyRu0v9NFJqv7tXmnGucXnOrjJcC1sVOHp1wCDDdvZGqoajDxNaOhu+5GJsDxY5KoKVQ8y+qkxvD+BShQ55HXh9tm4xa1Z03A/pow=]'
  securityToken: '![ezgKe8L8lJEHWR5mEVMpD+Pz+n51KJ33oOgswEgKTMs=]'